const HARDCODED_VARIATIONS: Record<string, string[]> = {
  toys: ['Bear Toy', 'Car Toy', 'Spinner Toy', 'Swing Toy'],
  toy: ['Bear Toy', 'Car Toy', 'Spinner Toy', 'Swing Toy'],
  vehicles: ['Car', 'Bus', 'Truck', 'Bike'],
  vehicle: ['Car', 'Bus', 'Truck', 'Bike'],
  cars: ['Car', 'Bus', 'Truck', 'Bike'],
  car: ['Sedan', 'SUV', 'Sports Car', 'Truck'],
  animals: ['Cat', 'Dog', 'Rabbit', 'Bear'],
  animal: ['Cat', 'Dog', 'Rabbit', 'Bear'],
  pets: ['Cat', 'Dog', 'Rabbit', 'Hamster'],
  pet: ['Cat', 'Dog', 'Rabbit', 'Hamster'],
  food: ['Cookie', 'Cupcake', 'Ice Cream', 'Pizza Slice'],
  foods: ['Cookie', 'Cupcake', 'Ice Cream', 'Pizza Slice'],
  snacks: ['Cookie', 'Cupcake', 'Chips', 'Candy'],
  snack: ['Cookie', 'Cupcake', 'Chips', 'Candy'],
  fruits: ['Apple', 'Banana', 'Strawberry', 'Orange'],
  fruit: ['Apple', 'Banana', 'Strawberry', 'Orange'],
  vegetables: ['Carrot', 'Tomato', 'Broccoli', 'Bell Pepper'],
  vegetable: ['Carrot', 'Tomato', 'Broccoli', 'Bell Pepper'],
  tools: ['Hammer', 'Wrench', 'Screwdriver', 'Pliers'],
  tool: ['Hammer', 'Wrench', 'Screwdriver', 'Pliers'],
  instruments: ['Guitar', 'Piano', 'Drums', 'Violin'],
  instrument: ['Guitar', 'Piano', 'Drums', 'Violin'],
  sports: ['Basketball', 'Soccer Ball', 'Tennis Racket', 'Baseball'],
  sport: ['Basketball', 'Soccer Ball', 'Tennis Racket', 'Baseball'],
  games: ['Chess Piece', 'Dice', 'Playing Card', 'Game Controller'],
  game: ['Chess Piece', 'Dice', 'Playing Card', 'Game Controller'],
  books: ['Open Book', 'Closed Book', 'Notebook', 'Comic Book'],
  book: ['Open Book', 'Closed Book', 'Notebook', 'Comic Book'],
  furniture: ['Chair', 'Table', 'Lamp', 'Bed'],
  electronics: ['Phone', 'Laptop', 'Headphones', 'Camera'],
  electronic: ['Phone', 'Laptop', 'Headphones', 'Camera'],
  clothing: ['T-Shirt', 'Jeans', 'Sneakers', 'Hat'],
  clothes: ['T-Shirt', 'Jeans', 'Sneakers', 'Hat'],
  shoes: ['Sneakers', 'Boots', 'Sandals', 'High Heels'],
  shoe: ['Sneakers', 'Boots', 'Sandals', 'High Heels'],
  accessories: ['Watch', 'Sunglasses', 'Backpack', 'Wallet'],
  accessory: ['Watch', 'Sunglasses', 'Backpack', 'Wallet'],
  plants: ['Cactus', 'Flower', 'Tree', 'Leaf'],
  plant: ['Cactus', 'Flower', 'Tree', 'Leaf'],
  flowers: ['Rose', 'Sunflower', 'Tulip', 'Daisy'],
  flower: ['Rose', 'Sunflower', 'Tulip', 'Daisy'],
  buildings: ['House', 'Skyscraper', 'Castle', 'Barn'],
  building: ['House', 'Skyscraper', 'Castle', 'Barn'],
  houses: ['House', 'Cabin', 'Mansion', 'Cottage'],
  house: ['House', 'Cabin', 'Mansion', 'Cottage'],
  planes: ['Airplane', 'Helicopter', 'Jet', 'Blimp'],
  plane: ['Airplane', 'Helicopter', 'Jet', 'Blimp'],
  ships: ['Sailboat', 'Speedboat', 'Cruise Ship', 'Yacht'],
  ship: ['Sailboat', 'Speedboat', 'Cruise Ship', 'Yacht'],
  boats: ['Sailboat', 'Speedboat', 'Rowboat', 'Yacht'],
  boat: ['Sailboat', 'Speedboat', 'Rowboat', 'Yacht'],
  bikes: ['Mountain Bike', 'Road Bike', 'BMX Bike', 'Electric Bike'],
  bike: ['Mountain Bike', 'Road Bike', 'BMX Bike', 'Electric Bike'],
  bicycles: ['Mountain Bike', 'Road Bike', 'BMX Bike', 'Electric Bike'],
  bicycle: ['Mountain Bike', 'Road Bike', 'BMX Bike', 'Electric Bike'],
  motorcycles: [
    'Sport Motorcycle',
    'Cruiser Motorcycle',
    'Dirt Bike',
    'Scooter',
  ],
  motorcycle: [
    'Sport Motorcycle',
    'Cruiser Motorcycle',
    'Dirt Bike',
    'Scooter',
  ],
}

export function getHardcodedVariations(category: string): string[] | null {
  const normalized = category.toLowerCase().trim()
  return HARDCODED_VARIATIONS[normalized] || null
}
